apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krakend-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alpha3b1/argodemo.git 
    targetRevision: HEAD
    path: krakend 
  destination: 
    server: https://kubernetes.default.svc
    namespace: krakend 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
