apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "name": "krakend",
      "port": 8080,
      "endpoints": [
        {
          "endpoint": "/health",
          "method": "GET",
          "output_encoding": "no-op",
          "extra_config": {},
          "backend": [
            {
              "host": [ "http://httpbin.org" ],
              "url_pattern": "/status/200"
            }
          ]
        }
      ]
    }
